### ISSUE TITLE
QR code support

### ISSUE THREAD

**Issue by Hacksore** [haykam821/ShortcutsPreview#7]
Allowing the bot to supply a QR code in the reddit or discord submission would be rather helpful for people browsing on the computer.

It's been suggested on the /r/shortcuts subreddit so I'm making an issue to track the progress.

**Comment by haykam821** [comment]
This is unfortunately unfeasible unless an image host is implemented. For now, users can use Handoff on their phone.

**Comment by Hacksore** [comment]
So relying on some third-party service could work but unsure if that's the goal here.

example:
https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=https://www.icloud.com/shortcuts/2b2ff2f5bf38437baaa3e2cd0b326354

**Comment by haykam821** [comment]
Using a third-party service is fine with me. The [privacy policy](http://goqr.me/de/rechtliches/datenschutz-goqrme.html) for that site is good and RoutineHub already uses it.
